# Directions: North = 0, East = 1, Top = 2, South = 3, West = 4, Bottom = 5
# Rotations Facing:  North = 0, East = 1, South = 2, West = 3, Don't Care = 4 
from tile import create_tile_direction_dict
from pyglm.glm import ivec3

TILE_SIZE = ivec3(3,4,3)

tile_quantity_limits = {("Farm_Wood_Corner",0): 1,
                        ("Farm_Wood_Corner",1): 1,
                        ("Farm_Wood_Corner",2): 1,
                        ("Farm_Wood_Corner",3): 1}

tile_directions_zero = {    "Farm_Wood_Ceiling":            {   0: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Ceiling",4)],
                                                                1: [("Farm_Wood_Wall",1),("Farm_Wood_Window",1), ("Farm_Wood_Ceiling",4)],
                                                                2: [],
                                                                3: [("Farm_Wood_Wall",2),("Farm_Wood_Window",2), ("Farm_Wood_Ceiling",4)],
                                                                4: [("Farm_Wood_Wall",3),("Farm_Wood_Window",3), ("Farm_Wood_Ceiling",4)],
                                                                5: []},
                            "Farm_Wood_Wall":               {   0: [("Air", 4), ("Farm_Field_Side_Empty",2), ("Farm_Field_Side_Wheat",2), ("Farm_Field_Side_Carrot",2), ("Farm_Field_Side_Potato",2), ("Farm_Field_Side_Beet",2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2)],
                                                                1: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",0)],
                                                                2: [],
                                                                3: [("Farm_Wood_Wall",2),("Farm_Wood_Window",2), ("Farm_Wood_Ceiling",4)],
                                                                4: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",3)],
                                                                5: []},
                            "Farm_Wood_Window":               { 0: [("Air", 4), ("Farm_Field_Side_Empty",2), ("Farm_Field_Side_Wheat",2), ("Farm_Field_Side_Carrot",2), ("Farm_Field_Side_Potato",2), ("Farm_Field_Side_Beet",2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2)],
                                                                1: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",0)],
                                                                2: [],
                                                                3: [("Farm_Wood_Wall",2),("Farm_Wood_Window",2), ("Farm_Wood_Ceiling",4)],
                                                                4: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",3)],
                                                                5: []},
                            "Farm_Wood_Door":               {   0: [("Air", 4)],
                                                                1: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",0)],
                                                                2: [],
                                                                3: [("Farm_Wood_Wall",2),("Farm_Wood_Window",2), ("Farm_Wood_Ceiling",4)],
                                                                4: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",3)],
                                                                5: []},
                            "Farm_Wood_Corner":               { 0: [("Air", 4), ("Farm_Field_Side_Empty",2), ("Farm_Field_Side_Wheat",2), ("Farm_Field_Side_Carrot",2), ("Farm_Field_Side_Potato",2), ("Farm_Field_Side_Beet",2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2)],
                                                                1: [("Air", 4), ("Farm_Field_Side_Empty",3), ("Farm_Field_Side_Wheat",3), ("Farm_Field_Side_Carrot",3), ("Farm_Field_Side_Potato",3), ("Farm_Field_Side_Beet",3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3)],
                                                                2: [],
                                                                3: [("Farm_Wood_Wall",1),("Farm_Wood_Window",1), ("Farm_Wood_Corner",1)],
                                                                4: [("Farm_Wood_Wall",0),("Farm_Wood_Window",0), ("Farm_Wood_Corner",3)],
                                                                5: []},
                            "Farm_Field_Middle_Empty":      {   0: [("Farm_Field_Side_Empty", 0), ("Farm_Field_Middle_Empty",4)],
                                                                1: [("Farm_Field_Side_Empty", 1), ("Farm_Field_Middle_Empty",4)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Empty", 2), ("Farm_Field_Middle_Empty",4)],
                                                                4: [("Farm_Field_Side_Empty", 3), ("Farm_Field_Middle_Empty",4)],
                                                                5: []},
                            "Farm_Field_Side_Empty":        {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Farm_Field_Side_Empty", 0), ("Farm_Field_Corner_Empty", 0)],
                                                                2: [],
                                                                3: [("Farm_Field_Middle_Empty", 4), ("Farm_Field_Side_Empty", 2)],
                                                                4: [("Farm_Field_Side_Empty", 0), ("Farm_Field_Corner_Empty", 3)],
                                                                5: []},
                            "Farm_Field_Corner_Empty":      {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 3), ("Farm_Field_Side_Wheat", 3), ("Farm_Field_Side_Carrot", 3), ("Farm_Field_Side_Potato", 3), ("Farm_Field_Side_Beet", 3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3),
                                                                    ("Farm_Wood_Wall",3), ("Farm_Wood_Window",3), ("Farm_Wood_Corner",2), ("Farm_Wood_Corner",3)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Empty", 1), ("Farm_Field_Corner_Empty", 1)],
                                                                4: [("Farm_Field_Side_Empty", 0), ("Farm_Field_Corner_Empty", 3)],
                                                                5: []},
                            "Farm_Field_Middle_Wheat":      {   0: [("Farm_Field_Side_Wheat", 0), ("Farm_Field_Middle_Wheat",4)],
                                                                1: [("Farm_Field_Side_Wheat", 1), ("Farm_Field_Middle_Wheat",4)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Wheat", 2), ("Farm_Field_Middle_Wheat",4)],
                                                                4: [("Farm_Field_Side_Wheat", 3), ("Farm_Field_Middle_Wheat",4)],
                                                                5: []},
                            "Farm_Field_Side_Wheat":        {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Farm_Field_Side_Wheat", 0), ("Farm_Field_Corner_Wheat", 0)],
                                                                2: [],
                                                                3: [("Farm_Field_Middle_Wheat", 4), ("Farm_Field_Side_Wheat", 2)],
                                                                4: [("Farm_Field_Side_Wheat", 0), ("Farm_Field_Corner_Wheat", 3)],
                                                                5: []},
                            "Farm_Field_Corner_Wheat":      {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 3), ("Farm_Field_Side_Wheat", 3), ("Farm_Field_Side_Carrot", 3), ("Farm_Field_Side_Potato", 3), ("Farm_Field_Side_Beet", 3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3),
                                                                    ("Farm_Wood_Wall",3), ("Farm_Wood_Window",3), ("Farm_Wood_Corner",2), ("Farm_Wood_Corner",3)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Wheat", 1), ("Farm_Field_Corner_Wheat", 1)],
                                                                4: [("Farm_Field_Side_Wheat", 0), ("Farm_Field_Corner_Wheat", 3)],
                                                                5: []},
                            "Farm_Field_Middle_Carrot":      {   0: [("Farm_Field_Side_Carrot", 0), ("Farm_Field_Middle_Carrot",4)],
                                                                1: [("Farm_Field_Side_Carrot", 1), ("Farm_Field_Middle_Carrot",4)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Carrot", 2), ("Farm_Field_Middle_Carrot",4)],
                                                                4: [("Farm_Field_Side_Carrot", 3), ("Farm_Field_Middle_Carrot",4)],
                                                                5: []},
                            "Farm_Field_Side_Carrot":        {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Farm_Field_Side_Carrot", 0), ("Farm_Field_Corner_Carrot", 0)],
                                                                2: [],
                                                                3: [("Farm_Field_Middle_Carrot", 4), ("Farm_Field_Side_Carrot", 2)],
                                                                4: [("Farm_Field_Side_Carrot", 0), ("Farm_Field_Corner_Carrot", 3)],
                                                                5: []},
                            "Farm_Field_Corner_Carrot":      {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 3), ("Farm_Field_Side_Wheat", 3), ("Farm_Field_Side_Carrot", 3), ("Farm_Field_Side_Potato", 3), ("Farm_Field_Side_Beet", 3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3),
                                                                    ("Farm_Wood_Wall",3), ("Farm_Wood_Window",3), ("Farm_Wood_Corner",2), ("Farm_Wood_Corner",3)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Carrot", 1), ("Farm_Field_Corner_Carrot", 1)],
                                                                4: [("Farm_Field_Side_Carrot", 0), ("Farm_Field_Corner_Carrot", 3)],
                                                                5: []},
                            "Farm_Field_Middle_Potato":      {   0: [("Farm_Field_Side_Potato", 0), ("Farm_Field_Middle_Potato",4)],
                                                                1: [("Farm_Field_Side_Potato", 1), ("Farm_Field_Middle_Potato",4)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Potato", 2), ("Farm_Field_Middle_Potato",4)],
                                                                4: [("Farm_Field_Side_Potato", 3), ("Farm_Field_Middle_Potato",4)],
                                                                5: []},
                            "Farm_Field_Side_Potato":        {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Farm_Field_Side_Potato", 0), ("Farm_Field_Corner_Potato", 0)],
                                                                2: [],
                                                                3: [("Farm_Field_Middle_Potato", 4), ("Farm_Field_Side_Potato", 2)],
                                                                4: [("Farm_Field_Side_Potato", 0), ("Farm_Field_Corner_Potato", 3)],
                                                                5: []},
                            "Farm_Field_Corner_Potato":      {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 3), ("Farm_Field_Side_Wheat", 3), ("Farm_Field_Side_Carrot", 3), ("Farm_Field_Side_Potato", 3), ("Farm_Field_Side_Beet", 3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3),
                                                                    ("Farm_Wood_Wall",3), ("Farm_Wood_Window",3), ("Farm_Wood_Corner",2), ("Farm_Wood_Corner",3)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Potato", 1), ("Farm_Field_Corner_Potato", 1)],
                                                                4: [("Farm_Field_Side_Potato", 0), ("Farm_Field_Corner_Potato", 3)],
                                                                5: []},
                            "Farm_Field_Middle_Beet":      {   0: [("Farm_Field_Side_Beet", 0), ("Farm_Field_Middle_Beet",4)],
                                                                1: [("Farm_Field_Side_Beet", 1), ("Farm_Field_Middle_Beet",4)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Beet", 2), ("Farm_Field_Middle_Beet",4)],
                                                                4: [("Farm_Field_Side_Beet", 3), ("Farm_Field_Middle_Beet",4)],
                                                                5: []},
                            "Farm_Field_Side_Beet":        {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Farm_Field_Side_Beet", 0), ("Farm_Field_Corner_Beet", 0)],
                                                                2: [],
                                                                3: [("Farm_Field_Middle_Beet", 4), ("Farm_Field_Side_Beet", 2)],
                                                                4: [("Farm_Field_Side_Beet", 0), ("Farm_Field_Corner_Beet", 3)],
                                                                5: []},
                            "Farm_Field_Corner_Beet":      {   0: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2),
                                                                    ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2)],
                                                                1: [("Air",4), 
                                                                    ("Farm_Field_Side_Empty", 3), ("Farm_Field_Side_Wheat", 3), ("Farm_Field_Side_Carrot", 3), ("Farm_Field_Side_Potato", 3), ("Farm_Field_Side_Beet", 3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3),
                                                                    ("Farm_Wood_Wall",3), ("Farm_Wood_Window",3), ("Farm_Wood_Corner",2), ("Farm_Wood_Corner",3)],
                                                                2: [],
                                                                3: [("Farm_Field_Side_Beet", 1), ("Farm_Field_Corner_Beet", 1)],
                                                                4: [("Farm_Field_Side_Beet", 0), ("Farm_Field_Corner_Beet", 3)],
                                                                5: []},
                            "Air":                          {   0: [("Air",4), ("Farm_Wood_Wall",2), ("Farm_Wood_Window",2), ("Farm_Wood_Corner",1), ("Farm_Wood_Corner",2),
                                                                    ("Farm_Field_Side_Empty",2), ("Farm_Field_Side_Wheat",2), ("Farm_Field_Side_Carrot",2), ("Farm_Field_Side_Potato",2), ("Farm_Field_Side_Beet",2),
                                                                    ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Carrot",1),  ("Farm_Field_Corner_Carrot",2), 
                                                                    ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Beet",1), ("Farm_Field_Corner_Beet",2)],
                                                                1: [("Air",4), ("Farm_Wood_Wall",3), ("Farm_Wood_Window",3), ("Farm_Wood_Corner",2), ("Farm_Wood_Corner",3),
                                                                    ("Farm_Field_Side_Empty",3), ("Farm_Field_Side_Wheat",3), ("Farm_Field_Side_Carrot",3), ("Farm_Field_Side_Potato",3), ("Farm_Field_Side_Beet",3),
                                                                    ("Farm_Field_Corner_Empty",2), ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Wheat",2), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Carrot",2),  ("Farm_Field_Corner_Carrot",3), 
                                                                    ("Farm_Field_Corner_Potato",2), ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Beet",2), ("Farm_Field_Corner_Beet",3)],
                                                                2: [],
                                                                3: [("Air",4), ("Farm_Wood_Wall",0), ("Farm_Wood_Window",0), ("Farm_Wood_Corner",3), ("Farm_Wood_Corner",0),
                                                                    ("Farm_Field_Side_Empty",0), ("Farm_Field_Side_Wheat",0), ("Farm_Field_Side_Carrot",0), ("Farm_Field_Side_Potato",0), ("Farm_Field_Side_Beet",0),
                                                                    ("Farm_Field_Corner_Empty",3), ("Farm_Field_Corner_Empty",0), ("Farm_Field_Corner_Wheat",3), ("Farm_Field_Corner_Wheat",0), ("Farm_Field_Corner_Carrot",3),  ("Farm_Field_Corner_Carrot",0), 
                                                                    ("Farm_Field_Corner_Potato",3), ("Farm_Field_Corner_Potato",0), ("Farm_Field_Corner_Beet",3), ("Farm_Field_Corner_Beet",0)],
                                                                4: [("Air",4), ("Farm_Wood_Wall",1), ("Farm_Wood_Window",1), ("Farm_Wood_Corner",0), ("Farm_Wood_Corner",1),
                                                                    ("Farm_Field_Side_Empty",1), ("Farm_Field_Side_Wheat",1), ("Farm_Field_Side_Carrot",1), ("Farm_Field_Side_Potato",1), ("Farm_Field_Side_Beet",1),
                                                                    ("Farm_Field_Corner_Empty",0), ("Farm_Field_Corner_Empty",1), ("Farm_Field_Corner_Wheat",0), ("Farm_Field_Corner_Wheat",1), ("Farm_Field_Corner_Carrot",0),  ("Farm_Field_Corner_Carrot",1), 
                                                                    ("Farm_Field_Corner_Potato",0), ("Farm_Field_Corner_Potato",1), ("Farm_Field_Corner_Beet",0), ("Farm_Field_Corner_Beet",1)],
                                                                5: []}}

tiles_borders_rotation_invariant = ["Air", "Farm_Wood_Ceiling", "Farm_Field_Middle_Empty", "Farm_Field_Middle_Wheat", "Farm_Field_Middle_Carrot", "Farm_Field_Middle_Potato", "Farm_Field_Middle_Beet"]

tile_directions = {}
for name, rot_zero_dict in tile_directions_zero.items():
    if name in tiles_borders_rotation_invariant:
        tile_directions.update({(name, 4): rot_zero_dict})
    else:
        tile_directions.update(create_tile_direction_dict(name, rot_zero_dict))

tile_weights = {    "Farm_Wood_Ceiling": 5,
                    "Farm_Wood_Wall": 10,
                    "Farm_Wood_Door": 1,
                    "Farm_Wood_Window": 10,
                    "Farm_Wood_Corner": 20,
                    "Farm_Field_Middle_Empty": 20,
                    "Farm_Field_Side_Empty": 10,
                    "Farm_Field_Corner_Empty": 1,
                    "Farm_Field_Middle_Wheat": 100,
                    "Farm_Field_Side_Wheat": 50,
                    "Farm_Field_Corner_Wheat": 5,
                    "Farm_Field_Middle_Carrot": 80,
                    "Farm_Field_Side_Carrot": 40,
                    "Farm_Field_Corner_Carrot": 4,
                    "Farm_Field_Middle_Potato": 80,
                    "Farm_Field_Side_Potato": 40,
                    "Farm_Field_Corner_Potato": 4,
                    "Farm_Field_Middle_Beet": 40,
                    "Farm_Field_Side_Beet": 20,
                    "Farm_Field_Corner_Beet": 2,
                    "Air": 1}

variation_weights = {   "Farm_Wood_Wall":   {"Farm_Wood_Wall#0": 5, "Farm_Wood_Wall#1": 2, "Farm_Wood_Wall#2": 2, "Farm_Wood_Wall#3": 2, "Farm_Wood_Wall#4": 2, "Farm_Wood_Wall#5": 2},
                        "Farm_Wood_Window": {"Farm_Wood_Window#0": 5, "Farm_Wood_Window#1": 2, "Farm_Wood_Window#2": 2, "Farm_Wood_Window#3": 2, "Farm_Wood_Window#4": 2},
                        "Farm_Wood_Corner": {"Farm_Wood_Corner#0": 5, "Farm_Wood_Corner#1": 2, "Farm_Wood_Corner#2": 2, "Farm_Wood_Corner#3": 2, "Farm_Wood_Corner#4": 2, "Farm_Wood_Corner#5": 2},
                        "Farm_Field_Middle_Empty": {"Farm_Field_Middle_Empty#0": 2, "Farm_Field_Middle_Empty#1": 1, "Farm_Field_Middle_Empty#2": 1},
                        "Farm_Field_Middle_Wheat": {"Farm_Field_Middle_Wheat#0": 2, "Farm_Field_Middle_Wheat#1": 1, "Farm_Field_Middle_Wheat#2": 1},
                        "Farm_Field_Middle_Carrot": {"Farm_Field_Middle_Carrot#0": 2, "Farm_Field_Middle_Carrot#1": 1, "Farm_Field_Middle_Carrot#2": 1},
                        "Farm_Field_Middle_Potato": {"Farm_Field_Middle_Potato#0": 2, "Farm_Field_Middle_Potato#1": 1, "Farm_Field_Middle_Potato#2": 1},
                        "Farm_Field_Middle_Beet": {"Farm_Field_Middle_Beet#0": 2, "Farm_Field_Middle_Beet#1": 1, "Farm_Field_Middle_Beet#2": 1}}


tiles_possible_all = [  ("Farm_Wood_Ceiling", 4),
                        ("Farm_Wood_Wall", 0), ("Farm_Wood_Wall", 1), ("Farm_Wood_Wall", 2), ("Farm_Wood_Wall", 3),
                        ("Farm_Wood_Door", 0), ("Farm_Wood_Door", 1), ("Farm_Wood_Door", 2), ("Farm_Wood_Door", 3),
                        ("Farm_Wood_Window", 0), ("Farm_Wood_Window", 1), ("Farm_Wood_Window", 2), ("Farm_Wood_Window", 3),
                        ("Farm_Wood_Corner", 0), ("Farm_Wood_Corner", 1), ("Farm_Wood_Corner", 2), ("Farm_Wood_Corner", 3),
                        ("Farm_Field_Side_Empty", 0), ("Farm_Field_Side_Empty", 1), ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Empty", 3),
                        ("Farm_Field_Side_Wheat", 0), ("Farm_Field_Side_Wheat", 1), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Wheat", 3),
                        ("Farm_Field_Side_Carrot", 0), ("Farm_Field_Side_Carrot", 1), ("Farm_Field_Side_Carrot", 2), ("Farm_Field_Side_Carrot", 3),
                        ("Farm_Field_Side_Potato", 0), ("Farm_Field_Side_Potato", 1), ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Potato", 3),
                        ("Farm_Field_Side_Beet", 0), ("Farm_Field_Side_Beet", 1), ("Farm_Field_Side_Beet", 2), ("Farm_Field_Side_Beet", 3),
                        ("Farm_Field_Corner_Empty", 0), ("Farm_Field_Corner_Empty", 1), ("Farm_Field_Corner_Empty", 2), ("Farm_Field_Corner_Empty", 3),
                        ("Farm_Field_Corner_Wheat", 0), ("Farm_Field_Corner_Wheat", 1), ("Farm_Field_Corner_Wheat", 2), ("Farm_Field_Corner_Wheat", 3),
                        ("Farm_Field_Corner_Carrot", 0), ("Farm_Field_Corner_Carrot", 1), ("Farm_Field_Corner_Carrot", 2), ("Farm_Field_Corner_Carrot", 3),
                        ("Farm_Field_Corner_Potato", 0), ("Farm_Field_Corner_Potato", 1), ("Farm_Field_Corner_Potato", 2), ("Farm_Field_Corner_Potato", 3),
                        ("Farm_Field_Corner_Beet", 0), ("Farm_Field_Corner_Beet", 1), ("Farm_Field_Corner_Beet", 2), ("Farm_Field_Corner_Beet", 3),
                        ("Farm_Field_Middle_Empty",4), ("Farm_Field_Middle_Wheat",4), ("Farm_Field_Middle_Carrot",4), ("Farm_Field_Middle_Potato",4), ("Farm_Field_Middle_Beet",4),
                        ("Air", 4)]

tiles_possible_inner = tiles_possible_all
tiles_possible_edge_north = [   ("Farm_Wood_Wall", 0), ("Farm_Wood_Door", 0), ("Farm_Wood_Window", 0), ("Farm_Wood_Corner", 0), ("Farm_Wood_Corner", 3), 
                                ("Farm_Field_Side_Empty", 0), ("Farm_Field_Side_Wheat", 0), ("Farm_Field_Side_Carrot", 0),
                                ("Farm_Field_Side_Potato", 0), ("Farm_Field_Side_Beet", 0), 
                                ("Farm_Field_Corner_Empty", 0), ("Farm_Field_Corner_Empty", 3),
                                ("Farm_Field_Corner_Wheat", 0), ("Farm_Field_Corner_Wheat", 3),
                                ("Farm_Field_Corner_Carrot", 0), ("Farm_Field_Corner_Carrot", 3),
                                ("Farm_Field_Corner_Potato", 0), ("Farm_Field_Corner_Potato", 3),
                                ("Farm_Field_Corner_Beet", 0), ("Farm_Field_Corner_Beet", 3),
                                ("Air", 4)]

tiles_possible_edge_east =  [   ("Farm_Wood_Wall", 1), ("Farm_Wood_Door", 1), ("Farm_Wood_Window", 1), ("Farm_Wood_Corner", 1), ("Farm_Wood_Corner", 0), 
                                ("Farm_Field_Side_Empty", 1), ("Farm_Field_Side_Wheat", 1), ("Farm_Field_Side_Carrot", 1),
                                ("Farm_Field_Side_Potato", 1), ("Farm_Field_Side_Beet", 1), 
                                ("Farm_Field_Corner_Empty", 1), ("Farm_Field_Corner_Empty", 0),
                                ("Farm_Field_Corner_Wheat", 1), ("Farm_Field_Corner_Wheat", 0),
                                ("Farm_Field_Corner_Carrot", 1), ("Farm_Field_Corner_Carrot", 0),
                                ("Farm_Field_Corner_Potato", 1), ("Farm_Field_Corner_Potato", 0),
                                ("Farm_Field_Corner_Beet", 1), ("Farm_Field_Corner_Beet", 0),
                                ("Air", 4)]

tiles_possible_edge_top = tiles_possible_all

tiles_possible_edge_south = [   ("Farm_Wood_Wall", 2), ("Farm_Wood_Door", 2), ("Farm_Wood_Window", 2), ("Farm_Wood_Corner", 2), ("Farm_Wood_Corner", 1), 
                                ("Farm_Field_Side_Empty", 2), ("Farm_Field_Side_Wheat", 2), ("Farm_Field_Side_Carrot", 2),
                                ("Farm_Field_Side_Potato", 2), ("Farm_Field_Side_Beet", 2), 
                                ("Farm_Field_Corner_Empty", 2), ("Farm_Field_Corner_Empty", 1),
                                ("Farm_Field_Corner_Wheat", 2), ("Farm_Field_Corner_Wheat", 1),
                                ("Farm_Field_Corner_Carrot", 2), ("Farm_Field_Corner_Carrot", 1),
                                ("Farm_Field_Corner_Potato", 2), ("Farm_Field_Corner_Potato", 1),
                                ("Farm_Field_Corner_Beet", 2), ("Farm_Field_Corner_Beet", 1),
                                ("Air", 4)]


tiles_possible_edge_west =  [   ("Farm_Wood_Wall", 3), ("Farm_Wood_Door", 3), ("Farm_Wood_Window", 3), ("Farm_Wood_Corner", 3), ("Farm_Wood_Corner", 2), 
                                ("Farm_Field_Side_Empty", 3), ("Farm_Field_Side_Wheat", 3), ("Farm_Field_Side_Carrot", 3),
                                ("Farm_Field_Side_Potato", 3), ("Farm_Field_Side_Beet", 3), 
                                ("Farm_Field_Corner_Empty", 3), ("Farm_Field_Corner_Empty", 2),
                                ("Farm_Field_Corner_Wheat", 3), ("Farm_Field_Corner_Wheat", 2),
                                ("Farm_Field_Corner_Carrot", 3), ("Farm_Field_Corner_Carrot", 2),
                                ("Farm_Field_Corner_Potato", 3), ("Farm_Field_Corner_Potato", 2),
                                ("Farm_Field_Corner_Beet", 3), ("Farm_Field_Corner_Beet", 2),
                                ("Air", 4)]

tiles_possible_edge_bottom = tiles_possible_all


tile_rules = [  tiles_possible_all,
                tiles_possible_inner,
                tiles_possible_edge_north,
                tiles_possible_edge_east,
                tiles_possible_edge_top,
                tiles_possible_edge_south,
                tiles_possible_edge_west,
                tiles_possible_edge_bottom]
