# Directions: North = 0, East = 1, Top = 2, South = 3, West = 4, Bottom = 5
# Rotations Facing:  North = 0, East = 1, South = 2, West = 3, Don't Care = 4
from ...tile import create_tile_direction_dict
from ...tile import ROT_NORTH, ROT_EAST, ROT_SOUTH, ROT_WEST, ROT_ANY
from ...tile import ROT_CNR_NE, ROT_CNR_SE, ROT_CNR_SW, ROT_CNR_NW
from ...tile import DIR_NORTH, DIR_EAST, DIR_TOP, DIR_SOUTH, DIR_WEST, DIR_BOTTOM
from pyglm.glm import ivec3

TILE_SIZE = ivec3(3,4,3)

tile_quantity_limits = {("Farm_Wood_Corner", ROT_CNR_NE): 1,
                        ("Farm_Wood_Corner", ROT_CNR_SE): 1,
                        ("Farm_Wood_Corner", ROT_CNR_SW): 1,
                        ("Farm_Wood_Corner", ROT_CNR_NW): 1}

tile_directions_zero = {    "Farm_Wood_Ceiling":            {   DIR_NORTH: [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Wood_Wall", ROT_EAST),("Farm_Wood_Window", ROT_EAST), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Wood_Wall", ROT_SOUTH),("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Wood_Wall", ROT_WEST),("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Wood_Wall":               {   DIR_NORTH: [("Air", ROT_ANY), ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Wood_Wall", ROT_SOUTH),("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Wood_Window":               { DIR_NORTH: [("Air", ROT_ANY), ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Wood_Wall", ROT_SOUTH),("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Wood_Door":               {   DIR_NORTH: [("Air", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Wood_Wall", ROT_SOUTH),("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Ceiling", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Wood_Corner":               { DIR_NORTH: [("Air", ROT_ANY), ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Wood_Wall", ROT_EAST),("Farm_Wood_Window", ROT_EAST), ("Farm_Wood_Corner", ROT_EAST)],
                                                                DIR_WEST:  [("Farm_Wood_Wall", ROT_NORTH),("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Middle_Empty":      {   DIR_NORTH: [("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Middle_Empty", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Field_Side_Empty", ROT_EAST), ("Farm_Field_Middle_Empty", ROT_ANY)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Middle_Empty", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Middle_Empty", ROT_ANY)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Side_Empty":        {   DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Corner_Empty", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Middle_Empty", ROT_ANY), ("Farm_Field_Side_Empty", ROT_SOUTH)],
                                                                DIR_WEST:  [("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Corner_Empty", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Corner_Empty":      {   DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                                                                            ("Farm_Wood_Wall", ROT_WEST), ("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Empty", ROT_EAST), ("Farm_Field_Corner_Empty", ROT_CNR_SE)],
                                                                DIR_WEST:  [("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Corner_Empty", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Middle_Wheat":      {   DIR_NORTH: [("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Middle_Wheat", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Field_Side_Wheat", ROT_EAST), ("Farm_Field_Middle_Wheat", ROT_ANY)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Middle_Wheat", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Middle_Wheat", ROT_ANY)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Side_Wheat":        {   DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Corner_Wheat", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Middle_Wheat", ROT_ANY), ("Farm_Field_Side_Wheat", ROT_SOUTH)],
                                                                DIR_WEST:  [("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Corner_Wheat", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Corner_Wheat":      {   DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                                                                            ("Farm_Wood_Wall", ROT_WEST), ("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Wheat", ROT_EAST), ("Farm_Field_Corner_Wheat", ROT_CNR_SE)],
                                                                DIR_WEST:  [("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Corner_Wheat", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Middle_Carrot":      {  DIR_NORTH: [("Farm_Field_Side_Carrot", ROT_NORTH), ("Farm_Field_Middle_Carrot", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Field_Side_Carrot", ROT_EAST), ("Farm_Field_Middle_Carrot", ROT_ANY)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Middle_Carrot", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Middle_Carrot", ROT_ANY)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Side_Carrot":        {  DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Field_Side_Carrot", ROT_NORTH), ("Farm_Field_Corner_Carrot", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Middle_Carrot", ROT_ANY), ("Farm_Field_Side_Carrot", ROT_SOUTH)],
                                                                DIR_WEST:  [("Farm_Field_Side_Carrot", ROT_NORTH), ("Farm_Field_Corner_Carrot", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Corner_Carrot":      {  DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                                                                            ("Farm_Wood_Wall", ROT_WEST), ("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Carrot", ROT_EAST), ("Farm_Field_Corner_Carrot", ROT_CNR_SE)],
                                                                DIR_WEST:  [("Farm_Field_Side_Carrot", ROT_NORTH), ("Farm_Field_Corner_Carrot", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Middle_Potato":      {   DIR_NORTH:[("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Middle_Potato", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Field_Side_Potato", ROT_EAST), ("Farm_Field_Middle_Potato", ROT_ANY)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Middle_Potato", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Middle_Potato", ROT_ANY)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Side_Potato":        {  DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Corner_Potato", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Middle_Potato", ROT_ANY), ("Farm_Field_Side_Potato", ROT_SOUTH)],
                                                                DIR_WEST:  [("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Corner_Potato", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Corner_Potato":      {  DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                                                                            ("Farm_Wood_Wall", ROT_WEST), ("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Potato", ROT_EAST), ("Farm_Field_Corner_Potato", ROT_CNR_SE)],
                                                                DIR_WEST:  [("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Corner_Potato", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Middle_Beet":      {    DIR_NORTH: [("Farm_Field_Side_Beet", ROT_NORTH), ("Farm_Field_Middle_Beet", ROT_ANY)],
                                                                DIR_EAST:  [("Farm_Field_Side_Beet", ROT_EAST), ("Farm_Field_Middle_Beet", ROT_ANY)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Beet", ROT_SOUTH), ("Farm_Field_Middle_Beet", ROT_ANY)],
                                                                DIR_WEST:  [("Farm_Field_Side_Beet", ROT_WEST), ("Farm_Field_Middle_Beet", ROT_ANY)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Side_Beet":        {    DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Farm_Field_Side_Beet", ROT_NORTH), ("Farm_Field_Corner_Beet", ROT_CNR_NE)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Middle_Beet", ROT_ANY), ("Farm_Field_Side_Beet", ROT_SOUTH)],
                                                                DIR_WEST:  [("Farm_Field_Side_Beet", ROT_NORTH), ("Farm_Field_Corner_Beet", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},

                            "Farm_Field_Corner_Beet":      {    DIR_NORTH: [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                                                            ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), 
                                                                            ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                                                                            ("Farm_Wood_Wall", ROT_WEST), ("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Farm_Field_Side_Beet", ROT_EAST), ("Farm_Field_Corner_Beet", ROT_CNR_SE)],
                                                                DIR_WEST:  [("Farm_Field_Side_Beet", ROT_NORTH), ("Farm_Field_Corner_Beet", ROT_CNR_NW)],
                                                                DIR_BOTTOM:[]},
                                                                
                            "Air":                          {   DIR_NORTH: [("Air", ROT_ANY), ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW),
                                                                            ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW)],
                                                                DIR_EAST:  [("Air", ROT_ANY), ("Farm_Wood_Wall", ROT_CNR_NW), ("Farm_Wood_Window", ROT_CNR_NW), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW),
                                                                            ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST), ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NW), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW)],
                                                                DIR_TOP:   [],
                                                                DIR_SOUTH: [("Air", ROT_ANY), ("Farm_Wood_Wall", ROT_NORTH), ("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NW), ("Farm_Wood_Corner", ROT_CNR_NE),
                                                                            ("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Side_Carrot", ROT_NORTH), ("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Side_Beet", ROT_NORTH),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Empty", ROT_CNR_NE), ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_NE), ("Farm_Field_Corner_Carrot", ROT_CNR_NW),  ("Farm_Field_Corner_Carrot", ROT_CNR_NE), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Potato", ROT_CNR_NE), ("Farm_Field_Corner_Beet", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_NE)],
                                                                DIR_WEST:  [("Air", ROT_ANY), ("Farm_Wood_Wall", ROT_EAST), ("Farm_Wood_Window", ROT_EAST), ("Farm_Wood_Corner", ROT_CNR_NE), ("Farm_Wood_Corner", ROT_EAST),
                                                                            ("Farm_Field_Side_Empty", ROT_EAST), ("Farm_Field_Side_Wheat", ROT_EAST), ("Farm_Field_Side_Carrot", ROT_EAST), ("Farm_Field_Side_Potato", ROT_EAST), ("Farm_Field_Side_Beet", ROT_EAST),
                                                                            ("Farm_Field_Corner_Empty", ROT_CNR_NE), ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_NE), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Carrot", ROT_CNR_NE),  ("Farm_Field_Corner_Carrot", ROT_CNR_SE), 
                                                                            ("Farm_Field_Corner_Potato", ROT_CNR_NE), ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_NE), ("Farm_Field_Corner_Beet", ROT_CNR_SE)],
                                                                DIR_BOTTOM:[]}}

tiles_borders_rotation_invariant = ["Air", "Farm_Wood_Ceiling", "Farm_Field_Middle_Empty", "Farm_Field_Middle_Wheat", "Farm_Field_Middle_Carrot", "Farm_Field_Middle_Potato", "Farm_Field_Middle_Beet"]

tile_directions = {}
for name, rot_zero_dict in tile_directions_zero.items():
    if name in tiles_borders_rotation_invariant:
        tile_directions.update({(name, ROT_ANY): rot_zero_dict})
    else:
        tile_directions.update(create_tile_direction_dict(name, rot_zero_dict))

tile_weights = {    "Farm_Wood_Ceiling": 5,
                    "Farm_Wood_Wall": 10,
                    "Farm_Wood_Door": 1,
                    "Farm_Wood_Window": 10,
                    "Farm_Wood_Corner": 30,
                    "Farm_Field_Middle_Empty": 20,
                    "Farm_Field_Side_Empty": 2,
                    "Farm_Field_Corner_Empty": 1,
                    "Farm_Field_Middle_Wheat": 100,
                    "Farm_Field_Side_Wheat": 10,
                    "Farm_Field_Corner_Wheat": 5,
                    "Farm_Field_Middle_Carrot": 80,
                    "Farm_Field_Side_Carrot": 8,
                    "Farm_Field_Corner_Carrot": 4,
                    "Farm_Field_Middle_Potato": 80,
                    "Farm_Field_Side_Potato": 8,
                    "Farm_Field_Corner_Potato": 4,
                    "Farm_Field_Middle_Beet": 40,
                    "Farm_Field_Side_Beet": 4,
                    "Farm_Field_Corner_Beet": 2,
                    "Air": 1}

variation_weights = {   "Farm_Wood_Wall":   {"Farm_Wood_Wall#0": 5, "Farm_Wood_Wall#1": 2, "Farm_Wood_Wall#2": 2, "Farm_Wood_Wall#3": 2, "Farm_Wood_Wall#4": 2, "Farm_Wood_Wall#5": 2},
                        "Farm_Wood_Window": {"Farm_Wood_Window#0": 5, "Farm_Wood_Window#1": 2, "Farm_Wood_Window#2": 2, "Farm_Wood_Window#3": 2, "Farm_Wood_Window#4": 2},
                        "Farm_Wood_Corner": {"Farm_Wood_Corner#0": 5, "Farm_Wood_Corner#1": 2, "Farm_Wood_Corner#2": 2, "Farm_Wood_Corner#3": 2, "Farm_Wood_Corner#4": 2, "Farm_Wood_Corner#5": 2},
                        "Farm_Field_Middle_Empty": {"Farm_Field_Middle_Empty#0": 2, "Farm_Field_Middle_Empty#1": 1, "Farm_Field_Middle_Empty#2": 1},
                        "Farm_Field_Middle_Wheat": {"Farm_Field_Middle_Wheat#0": 2, "Farm_Field_Middle_Wheat#1": 1, "Farm_Field_Middle_Wheat#2": 1},
                        "Farm_Field_Middle_Carrot": {"Farm_Field_Middle_Carrot#0": 2, "Farm_Field_Middle_Carrot#1": 1, "Farm_Field_Middle_Carrot#2": 1},
                        "Farm_Field_Middle_Potato": {"Farm_Field_Middle_Potato#0": 2, "Farm_Field_Middle_Potato#1": 1, "Farm_Field_Middle_Potato#2": 1},
                        "Farm_Field_Middle_Beet": {"Farm_Field_Middle_Beet#0": 2, "Farm_Field_Middle_Beet#1": 1, "Farm_Field_Middle_Beet#2": 1}}


tiles_possible_all = [  ("Farm_Wood_Ceiling", ROT_ANY),
                        ("Farm_Wood_Wall", ROT_NORTH), ("Farm_Wood_Wall", ROT_EAST), ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Wall", ROT_WEST),
                        ("Farm_Wood_Door", ROT_NORTH), ("Farm_Wood_Door", ROT_EAST), ("Farm_Wood_Door", ROT_SOUTH), ("Farm_Wood_Door", ROT_WEST),
                        ("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Window", ROT_EAST), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Window", ROT_WEST),
                        ("Farm_Wood_Corner", ROT_CNR_NE), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_NW),
                        ("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Side_Empty", ROT_EAST), ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Empty", ROT_WEST),
                        ("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Side_Wheat", ROT_EAST), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_WEST),
                        ("Farm_Field_Side_Carrot", ROT_NORTH), ("Farm_Field_Side_Carrot", ROT_EAST), ("Farm_Field_Side_Carrot", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_WEST),
                        ("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Side_Potato", ROT_EAST), ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Potato", ROT_WEST),
                        ("Farm_Field_Side_Beet", ROT_NORTH), ("Farm_Field_Side_Beet", ROT_EAST), ("Farm_Field_Side_Beet", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_WEST),
                        ("Farm_Field_Corner_Empty", ROT_CNR_NE), ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_NW),
                        ("Farm_Field_Corner_Wheat", ROT_CNR_NE), ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_NW),
                        ("Farm_Field_Corner_Carrot", ROT_CNR_NE), ("Farm_Field_Corner_Carrot", ROT_CNR_SE), ("Farm_Field_Corner_Carrot", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_NW),
                        ("Farm_Field_Corner_Potato", ROT_CNR_NE), ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_NW),
                        ("Farm_Field_Corner_Beet", ROT_CNR_NE), ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                        ("Farm_Field_Middle_Empty", ROT_ANY), ("Farm_Field_Middle_Wheat", ROT_ANY), ("Farm_Field_Middle_Carrot", ROT_ANY), ("Farm_Field_Middle_Potato", ROT_ANY), ("Farm_Field_Middle_Beet", ROT_ANY),
                        ("Air", ROT_ANY)]

tiles_possible_inner = tiles_possible_all
tiles_possible_edge_north = [   ("Farm_Wood_Wall", ROT_NORTH), ("Farm_Wood_Door", ROT_NORTH), ("Farm_Wood_Window", ROT_NORTH), ("Farm_Wood_Corner", ROT_CNR_NE), ("Farm_Wood_Corner", ROT_CNR_NW), 
                                ("Farm_Field_Side_Empty", ROT_NORTH), ("Farm_Field_Side_Wheat", ROT_NORTH), ("Farm_Field_Side_Carrot", ROT_NORTH),
                                ("Farm_Field_Side_Potato", ROT_NORTH), ("Farm_Field_Side_Beet", ROT_NORTH), 
                                ("Farm_Field_Corner_Empty", ROT_CNR_NE), ("Farm_Field_Corner_Empty", ROT_CNR_NW),
                                ("Farm_Field_Corner_Wheat", ROT_CNR_NE), ("Farm_Field_Corner_Wheat", ROT_CNR_NW),
                                ("Farm_Field_Corner_Carrot", ROT_CNR_NE), ("Farm_Field_Corner_Carrot", ROT_CNR_NW),
                                ("Farm_Field_Corner_Potato", ROT_CNR_NE), ("Farm_Field_Corner_Potato", ROT_CNR_NW),
                                ("Farm_Field_Corner_Beet", ROT_CNR_NE), ("Farm_Field_Corner_Beet", ROT_CNR_NW),
                                ("Air", ROT_ANY)]

tiles_possible_edge_east =  [   ("Farm_Wood_Wall", ROT_EAST), ("Farm_Wood_Door", ROT_EAST), ("Farm_Wood_Window", ROT_EAST), ("Farm_Wood_Corner", ROT_CNR_SE), ("Farm_Wood_Corner", ROT_CNR_NE), 
                                ("Farm_Field_Side_Empty", ROT_EAST), ("Farm_Field_Side_Wheat", ROT_EAST), ("Farm_Field_Side_Carrot", ROT_EAST),
                                ("Farm_Field_Side_Potato", ROT_EAST), ("Farm_Field_Side_Beet", ROT_EAST), 
                                ("Farm_Field_Corner_Empty", ROT_CNR_SE), ("Farm_Field_Corner_Empty", ROT_CNR_NE),
                                ("Farm_Field_Corner_Wheat", ROT_CNR_SE), ("Farm_Field_Corner_Wheat", ROT_CNR_NE),
                                ("Farm_Field_Corner_Carrot", ROT_CNR_SE), ("Farm_Field_Corner_Carrot", ROT_CNR_NE),
                                ("Farm_Field_Corner_Potato", ROT_CNR_SE), ("Farm_Field_Corner_Potato", ROT_CNR_NE),
                                ("Farm_Field_Corner_Beet", ROT_CNR_SE), ("Farm_Field_Corner_Beet", ROT_CNR_NE),
                                ("Air", ROT_ANY)]

tiles_possible_edge_top = tiles_possible_all

tiles_possible_edge_south = [   ("Farm_Wood_Wall", ROT_SOUTH), ("Farm_Wood_Door", ROT_SOUTH), ("Farm_Wood_Window", ROT_SOUTH), ("Farm_Wood_Corner", ROT_CNR_SW), ("Farm_Wood_Corner", ROT_CNR_SE), 
                                ("Farm_Field_Side_Empty", ROT_SOUTH), ("Farm_Field_Side_Wheat", ROT_SOUTH), ("Farm_Field_Side_Carrot", ROT_SOUTH),
                                ("Farm_Field_Side_Potato", ROT_SOUTH), ("Farm_Field_Side_Beet", ROT_SOUTH), 
                                ("Farm_Field_Corner_Empty", ROT_CNR_SW), ("Farm_Field_Corner_Empty", ROT_CNR_SE),
                                ("Farm_Field_Corner_Wheat", ROT_CNR_SW), ("Farm_Field_Corner_Wheat", ROT_CNR_SE),
                                ("Farm_Field_Corner_Carrot", ROT_CNR_SW), ("Farm_Field_Corner_Carrot", ROT_CNR_SE),
                                ("Farm_Field_Corner_Potato", ROT_CNR_SW), ("Farm_Field_Corner_Potato", ROT_CNR_SE),
                                ("Farm_Field_Corner_Beet", ROT_CNR_SW), ("Farm_Field_Corner_Beet", ROT_CNR_SE),
                                ("Air", ROT_ANY)]


tiles_possible_edge_west =  [   ("Farm_Wood_Wall", ROT_WEST), ("Farm_Wood_Door", ROT_WEST), ("Farm_Wood_Window", ROT_WEST), ("Farm_Wood_Corner", ROT_CNR_NW), ("Farm_Wood_Corner", ROT_CNR_SW), 
                                ("Farm_Field_Side_Empty", ROT_WEST), ("Farm_Field_Side_Wheat", ROT_WEST), ("Farm_Field_Side_Carrot", ROT_WEST),
                                ("Farm_Field_Side_Potato", ROT_WEST), ("Farm_Field_Side_Beet", ROT_WEST), 
                                ("Farm_Field_Corner_Empty", ROT_CNR_NW), ("Farm_Field_Corner_Empty", ROT_CNR_SW),
                                ("Farm_Field_Corner_Wheat", ROT_CNR_NW), ("Farm_Field_Corner_Wheat", ROT_CNR_SW),
                                ("Farm_Field_Corner_Carrot", ROT_CNR_NW), ("Farm_Field_Corner_Carrot", ROT_CNR_SW),
                                ("Farm_Field_Corner_Potato", ROT_CNR_NW), ("Farm_Field_Corner_Potato", ROT_CNR_SW),
                                ("Farm_Field_Corner_Beet", ROT_CNR_NW), ("Farm_Field_Corner_Beet", ROT_CNR_SW),
                                ("Air", ROT_ANY)]

tiles_possible_edge_bottom = tiles_possible_all


tile_rules = [  tiles_possible_all,
                tiles_possible_inner,
                tiles_possible_edge_north,
                tiles_possible_edge_east,
                tiles_possible_edge_top,
                tiles_possible_edge_south,
                tiles_possible_edge_west,
                tiles_possible_edge_bottom]
