"""
tile_directions = { "HouseGroundFloorWood_Ceiling": ["INSIDE", "INSIDE", "INSIDE", "INSIDE", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_Stairs": ["INSIDE", "INSIDE", "INSIDE", "INSIDE", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_WallN": ["OUTSIDE", "WALL_N", "INSIDE", "INSIDE", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_WallE": ["WALL_E", "OUTSIDE", "INSIDE", "WALL_E", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_WallS": ["INSIDE", "WALL_S", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_WallW": ["WALL_W", "INSIDE", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_DoorN": ["OUTSIDE", "WALL_N", "INSIDE", "INSIDE", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_DoorE": ["WALL_E", "OUTSIDE", "INSIDE", "WALL_E", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_DoorS": ["INSIDE", "WALL_S", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_DoorW": ["WALL_W", "INSIDE", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_WindowN": ["OUTSIDE", "WALL_N", "INSIDE", "INSIDE", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_WindowE": ["WALL_E", "OUTSIDE", "INSIDE", "WALL_E", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_WindowS": ["INSIDE", "WALL_S", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_WindowW": ["WALL_W", "INSIDE", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_CornerNE": ["OUTSIDE", "OUTSIDE", "INSIDE", "WALL_E", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_CornerSE": ["WALL_E", "OUTSIDE", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_CornerSW": ["WALL_W", "WALL_S", "INSIDE", "OUTSIDE", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_CornerNW": ["OUTSIDE", "WALL_N", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "Air" : ["OUTSIDE", "OUTSIDE", "OUTSIDE", "OUTSIDE", "OUTSIDE", "OUTSIDE"]}
"""

tile_directions = { "HouseGroundFloorWood_Ceiling": {0: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs", "HouseGroundFloorWood_WallN", "HouseGroundFloorWood_WindowN"],
                                                     1: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs", "HouseGroundFloorWood_WallE", "HouseGroundFloorWood_WindowE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs", "HouseGroundFloorWood_WallS", "HouseGroundFloorWood_WindowS"],
                                                     4: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs", "HouseGroundFloorWood_WallW", "HouseGroundFloorWood_WindowW"],
                                                     5: []},
                    "HouseGroundFloorWood_Stairs":  {0: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_WallN", "HouseGroundFloorWood_WindowN"],
                                                     1: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_WallE", "HouseGroundFloorWood_WindowE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_WallS", "HouseGroundFloorWood_WindowS"],
                                                     4: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_WallW", "HouseGroundFloorWood_WindowW"],
                                                     5: []},
                    "HouseGroundFloorWood_WallN":   {0: ["Air"],
                                                     1: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS"],
                                                     4: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNW"],
                                                     5: []},
                    "HouseGroundFloorWood_WallE":   {0: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerNE"],
                                                     1: ["Air"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerSE"],
                                                     4: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW"],
                                                     5: []},
                    "HouseGroundFloorWood_WallS":   {0: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN"],
                                                     1: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSE"],
                                                     2: [],
                                                     3: ["Air"],
                                                     4: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSW"],
                                                     5: []},
                    "HouseGroundFloorWood_WallW":   {0: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerNW"],
                                                     1: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerSW"],
                                                     4: ["Air"],
                                                     5: []},
                    "HouseGroundFloorWood_DoorN":   {0: ["Air"],
                                                     1: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS"],
                                                     4: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNW"],
                                                     5: []},
                    "HouseGroundFloorWood_DoorE":   {0: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerNE"],
                                                     1: ["Air"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerSE"],
                                                     4: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW"],
                                                     5: []},
                    "HouseGroundFloorWood_DoorS":   {0: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN"],
                                                     1: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSE"],
                                                     2: [],
                                                     3: ["Air"],
                                                     4: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSW"],
                                                     5: []},
                    "HouseGroundFloorWood_DoorW":   {0: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerNW"],
                                                     1: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerSW"],
                                                     4: ["Air"],
                                                     5: []},
                    "HouseGroundFloorWood_WindowN": {0: ["Air"],
                                                     1: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS"],
                                                     4: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNW"],
                                                     5: []},
                    "HouseGroundFloorWood_WindowE": {0: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerNE"],
                                                     1: ["Air"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerSE"],
                                                     4: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW"],
                                                     5: []},
                    "HouseGroundFloorWood_WindowS": {0: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN"],
                                                     1: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSE"],
                                                     2: [],
                                                     3: ["Air"],
                                                     4: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSW"],
                                                     5: []},
                    "HouseGroundFloorWood_WindowW": {0: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerNW"],
                                                     1: ["HouseGroundFloorWood_Ceiling", "HouseGroundFloorWood_Stairs","HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerSW"],
                                                     4: ["Air"],
                                                     5: []},
                    "HouseGroundFloorWood_CornerNE":{0: ["Air"],
                                                     1: ["Air"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerSE"],
                                                     4: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNW"],
                                                     5: []},
                    "HouseGroundFloorWood_CornerSE":{0: ["HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerNE"],
                                                     1: ["Air"],
                                                     2: [],
                                                     3: ["Air"],
                                                     4: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSW"],
                                                     5: []},
                    "HouseGroundFloorWood_CornerSW":{0: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerNW"],
                                                     1: ["HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSE"],
                                                     2: [],
                                                     3: ["Air"],
                                                     4: ["Air"],
                                                     5: []},
                    "HouseGroundFloorWood_CornerNW":{0: ["Air"],
                                                     1: ["HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNE"],
                                                     2: [],
                                                     3: ["HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerSW"],
                                                     4: ["Air"],
                                                     5: []},
                    "Air" :                         {0: ["Air","HouseGroundFloorWood_WallS","HouseGroundFloorWood_WindowS","HouseGroundFloorWood_CornerSE","HouseGroundFloorWood_CornerSW"],
                                                     1: ["Air","HouseGroundFloorWood_WallW","HouseGroundFloorWood_WindowW","HouseGroundFloorWood_CornerNW","HouseGroundFloorWood_CornerSW"],
                                                     2: ["Air"],
                                                     3: ["Air","HouseGroundFloorWood_WallN","HouseGroundFloorWood_WindowN","HouseGroundFloorWood_CornerNE","HouseGroundFloorWood_CornerNW"],
                                                     4: ["Air","HouseGroundFloorWood_WallE","HouseGroundFloorWood_WindowE","HouseGroundFloorWood_CornerNE","HouseGroundFloorWood_CornerSE"],
                                                     5: ["Air"]},}


tiles_possible_all = [  "HouseGroundFloorWood_Ceiling",
                        "HouseGroundFloorWood_Stairs",
                        "HouseGroundFloorWood_WallN",
                        "HouseGroundFloorWood_WallE",
                        "HouseGroundFloorWood_WallS",
                        "HouseGroundFloorWood_WallW",
                        "HouseGroundFloorWood_DoorN",
                        "HouseGroundFloorWood_DoorE",
                        "HouseGroundFloorWood_DoorS",
                        "HouseGroundFloorWood_DoorW",
                        "HouseGroundFloorWood_WindowN",
                        "HouseGroundFloorWood_WindowE",
                        "HouseGroundFloorWood_WindowS",
                        "HouseGroundFloorWood_WindowW",
                        "HouseGroundFloorWood_CornerNE",
                        "HouseGroundFloorWood_CornerSE",
                        "HouseGroundFloorWood_CornerSW",
                        "HouseGroundFloorWood_CornerNW",
                        "Air"]

tiles_possible_inner = ["HouseGroundFloorWood_Ceiling",
                        "HouseGroundFloorWood_Stairs",
                        "HouseGroundFloorWood_WallN",
                        "HouseGroundFloorWood_WallE",
                        "HouseGroundFloorWood_WallS",
                        "HouseGroundFloorWood_WallW",
                        "HouseGroundFloorWood_DoorN",
                        "HouseGroundFloorWood_DoorE",
                        "HouseGroundFloorWood_DoorS",
                        "HouseGroundFloorWood_DoorW",
                        "HouseGroundFloorWood_WindowN",
                        "HouseGroundFloorWood_WindowE",
                        "HouseGroundFloorWood_WindowS",
                        "HouseGroundFloorWood_WindowW",
                        "HouseGroundFloorWood_CornerNE",
                        "HouseGroundFloorWood_CornerSE",
                        "HouseGroundFloorWood_CornerSW",
                        "HouseGroundFloorWood_CornerNW",
                        "Air"]

tiles_possible_edge_north = [   "HouseGroundFloorWood_WallN",                           
                                "HouseGroundFloorWood_DoorN",                               
                                "HouseGroundFloorWood_WindowN",                               
                                "HouseGroundFloorWood_CornerNE",
                                "HouseGroundFloorWood_CornerNW",
                                "Air"]

tiles_possible_edge_east = [    "HouseGroundFloorWood_WallE",                           
                                "HouseGroundFloorWood_DoorE",                               
                                "HouseGroundFloorWood_WindowE",                               
                                "HouseGroundFloorWood_CornerNE",
                                "HouseGroundFloorWood_CornerSE",
                                "Air"]

tiles_possible_edge_top = [ "HouseGroundFloorWood_Ceiling",
                            "HouseGroundFloorWood_Stairs",
                            "HouseGroundFloorWood_WallN",
                            "HouseGroundFloorWood_WallE",
                            "HouseGroundFloorWood_WallS",
                            "HouseGroundFloorWood_WallW",
                            "HouseGroundFloorWood_DoorN",
                            "HouseGroundFloorWood_DoorE",
                            "HouseGroundFloorWood_DoorS",
                            "HouseGroundFloorWood_DoorW",
                            "HouseGroundFloorWood_WindowN",
                            "HouseGroundFloorWood_WindowE",
                            "HouseGroundFloorWood_WindowS",
                            "HouseGroundFloorWood_WindowW",
                            "HouseGroundFloorWood_CornerNE",
                            "HouseGroundFloorWood_CornerSE",
                            "HouseGroundFloorWood_CornerSW",
                            "HouseGroundFloorWood_CornerNW",
                            "Air"]

tiles_possible_edge_south = [   "HouseGroundFloorWood_WallS",                           
                                "HouseGroundFloorWood_DoorS",                               
                                "HouseGroundFloorWood_WindowS",                               
                                "HouseGroundFloorWood_CornerSE",
                                "HouseGroundFloorWood_CornerSW",
                                "Air"]

tiles_possible_edge_west = [    "HouseGroundFloorWood_WallW",                           
                                "HouseGroundFloorWood_DoorW",                               
                                "HouseGroundFloorWood_WindowW",                               
                                "HouseGroundFloorWood_CornerNW",
                                "HouseGroundFloorWood_CornerSW",
                                "Air"]

tiles_possible_edge_bottom = [  "HouseGroundFloorWood_Ceiling",
                                "HouseGroundFloorWood_Stairs",
                                "HouseGroundFloorWood_WallN",
                                "HouseGroundFloorWood_WallE",
                                "HouseGroundFloorWood_WallS",
                                "HouseGroundFloorWood_WallW",
                                "HouseGroundFloorWood_DoorN",
                                "HouseGroundFloorWood_DoorE",
                                "HouseGroundFloorWood_DoorS",
                                "HouseGroundFloorWood_DoorW",
                                "HouseGroundFloorWood_WindowN",
                                "HouseGroundFloorWood_WindowE",
                                "HouseGroundFloorWood_WindowS",
                                "HouseGroundFloorWood_WindowW",
                                "HouseGroundFloorWood_CornerNE",
                                "HouseGroundFloorWood_CornerSE",
                                "HouseGroundFloorWood_CornerSW",
                                "HouseGroundFloorWood_CornerNW",
                                "Air"]


tile_rules = [  tiles_possible_all,
                tiles_possible_inner,
                tiles_possible_edge_north,
                tiles_possible_edge_east,
                tiles_possible_edge_top,
                tiles_possible_edge_south,
                tiles_possible_edge_west,
                tiles_possible_edge_bottom]
