tile_directions = { "HouseGroundFloorWoodCeiling": ["INSIDE", "INSIDE", "INSIDE", "INSIDE"],
                    "HouseGroundFloorWoodStairs": ["INSIDE", "INSIDE", "INSIDE", "INSIDE"],
                    "HouseGroundFloorWoodWallN": ["OUTSIDE", "WALL_N", "INSIDE", "WALL_N"],
                    "HouseGroundFloorWoodWallE": ["WALL_E", "OUTSIDE", "WALL_E", "INSIDE"],
                    "HouseGroundFloorWoodWallS": ["INSIDE", "WALL_S", "OUTSIDE", "WALL_S"],
                    "HouseGroundFloorWoodWallW": ["WALL_W", "INSIDE", "WALL_W", "OUTSIDE"],
                    "HouseGroundFloorWoodDoorN": ["OUTSIDE", "WALL_N", "INSIDE", "WALL_N"],
                    "HouseGroundFloorWoodDoorE": ["WALL_E", "OUTSIDE", "WALL_E", "INSIDE"],
                    "HouseGroundFloorWoodDoorS": ["INSIDE", "WALL_S", "OUTSIDE", "WALL_S"],
                    "HouseGroundFloorWoodDoorW": ["WALL_W", "INSIDE", "WALL_W", "OUTSIDE"],
                    "HouseGroundFloorWoodWindowN": ["OUTSIDE", "WALL_N", "INSIDE", "WALL_N"],
                    "HouseGroundFloorWoodWindowE": ["WALL_E", "OUTSIDE", "WALL_E", "INSIDE"],
                    "HouseGroundFloorWoodWindowS": ["INSIDE", "WALL_S", "OUTSIDE", "WALL_S"],
                    "HouseGroundFloorWoodWindowW": ["WALL_W", "INSIDE", "WALL_W", "OUTSIDE"],
                    "HouseGroundFloorWoodCornerNE": ["OUTSIDE", "OUTSIDE", "WALL_E", "WALL_N"],
                    "HouseGroundFloorWoodCornerSE": ["WALL_E", "OUTSIDE", "OUTSIDE", "WALL_S"],
                    "HouseGroundFloorWoodCornerSW": ["WALL_W", "WALL_S", "OUTSIDE", "OUTSIDE"],
                    "HouseGroundFloorWoodCornerNW": ["OUTSIDE", "WALL_N", "WALL_W", "OUTSIDE"]}