tile_directions = { "HouseGroundFloorWood_Ceiling": ["INSIDE", "INSIDE", "INSIDE", "INSIDE", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_Stairs": ["INSIDE", "INSIDE", "INSIDE", "INSIDE", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_WallN": ["OUTSIDE", "WALL_N", "INSIDE", "INSIDE", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_WallE": ["WALL_E", "OUTSIDE", "INSIDE", "WALL_E", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_WallS": ["INSIDE", "WALL_S", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_WallW": ["WALL_W", "INSIDE", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_DoorN": ["OUTSIDE", "WALL_N", "INSIDE", "INSIDE", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_DoorE": ["WALL_E", "OUTSIDE", "INSIDE", "WALL_E", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_DoorS": ["INSIDE", "WALL_S", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_DoorW": ["WALL_W", "INSIDE", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_WindowN": ["OUTSIDE", "WALL_N", "INSIDE", "INSIDE", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_WindowE": ["WALL_E", "OUTSIDE", "INSIDE", "WALL_E", "INSIDE", "GROUND"],
                    "HouseGroundFloorWood_WindowS": ["INSIDE", "WALL_S", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_WindowW": ["WALL_W", "INSIDE", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_CornerNE": ["OUTSIDE", "OUTSIDE", "INSIDE", "WALL_E", "WALL_N", "GROUND"],
                    "HouseGroundFloorWood_CornerSE": ["WALL_E", "OUTSIDE", "INSIDE", "OUTSIDE", "WALL_S", "GROUND"],
                    "HouseGroundFloorWood_CornerSW": ["WALL_W", "WALL_S", "INSIDE", "OUTSIDE", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_CornerNW": ["OUTSIDE", "WALL_N", "INSIDE", "WALL_W", "OUTSIDE", "GROUND"],
                    "HouseGroundFloorWood_Air" : ["OUTSIDE", "OUTSIDE", "OUTSIDE", "OUTSIDE", "OUTSIDE", "OUTSIDE"]}

tiles_possible_all = [  "HouseGroundFloorWood_Ceiling",
                        "HouseGroundFloorWood_Stairs",
                        "HouseGroundFloorWood_WallN",
                        "HouseGroundFloorWood_WallE",
                        "HouseGroundFloorWood_WallS",
                        "HouseGroundFloorWood_WallW",
                        "HouseGroundFloorWood_DoorN",
                        "HouseGroundFloorWood_DoorE",
                        "HouseGroundFloorWood_DoorS",
                        "HouseGroundFloorWood_DoorW",
                        "HouseGroundFloorWood_WindowN",
                        "HouseGroundFloorWood_WindowE",
                        "HouseGroundFloorWood_WindowS",
                        "HouseGroundFloorWood_WindowW",
                        "HouseGroundFloorWood_CornerNE",
                        "HouseGroundFloorWood_CornerSE",
                        "HouseGroundFloorWood_CornerSW",
                        "HouseGroundFloorWood_CornerNW",
                        "HouseGroundFloorWood_Air"]

tiles_possible_inner = ["HouseGroundFloorWood_Ceiling",
                        "HouseGroundFloorWood_Stairs",
                        "HouseGroundFloorWood_WallN",
                        "HouseGroundFloorWood_WallE",
                        "HouseGroundFloorWood_WallS",
                        "HouseGroundFloorWood_WallW",
                        "HouseGroundFloorWood_DoorN",
                        "HouseGroundFloorWood_DoorE",
                        "HouseGroundFloorWood_DoorS",
                        "HouseGroundFloorWood_DoorW",
                        "HouseGroundFloorWood_WindowN",
                        "HouseGroundFloorWood_WindowE",
                        "HouseGroundFloorWood_WindowS",
                        "HouseGroundFloorWood_WindowW",
                        "HouseGroundFloorWood_CornerNE",
                        "HouseGroundFloorWood_CornerSE",
                        "HouseGroundFloorWood_CornerSW",
                        "HouseGroundFloorWood_CornerNW",
                        "HouseGroundFloorWood_Air"]

tiles_possible_edge_north = [   "HouseGroundFloorWood_WallN",                           
                                "HouseGroundFloorWood_DoorN",                               
                                "HouseGroundFloorWood_WindowN",                               
                                "HouseGroundFloorWood_CornerNE",
                                "HouseGroundFloorWood_CornerNW",
                                "HouseGroundFloorWood_Air"]

tiles_possible_edge_east = [    "HouseGroundFloorWood_WallE",                           
                                "HouseGroundFloorWood_DoorE",                               
                                "HouseGroundFloorWood_WindowE",                               
                                "HouseGroundFloorWood_CornerNE",
                                "HouseGroundFloorWood_CornerSE",
                                "HouseGroundFloorWood_Air"]

tiles_possible_edge_top = [ "HouseGroundFloorWood_Ceiling",
                            "HouseGroundFloorWood_Stairs",
                            "HouseGroundFloorWood_WallN",
                            "HouseGroundFloorWood_WallE",
                            "HouseGroundFloorWood_WallS",
                            "HouseGroundFloorWood_WallW",
                            "HouseGroundFloorWood_DoorN",
                            "HouseGroundFloorWood_DoorE",
                            "HouseGroundFloorWood_DoorS",
                            "HouseGroundFloorWood_DoorW",
                            "HouseGroundFloorWood_WindowN",
                            "HouseGroundFloorWood_WindowE",
                            "HouseGroundFloorWood_WindowS",
                            "HouseGroundFloorWood_WindowW",
                            "HouseGroundFloorWood_CornerNE",
                            "HouseGroundFloorWood_CornerSE",
                            "HouseGroundFloorWood_CornerSW",
                            "HouseGroundFloorWood_CornerNW",
                            "HouseGroundFloorWood_Air"]

tiles_possible_edge_south = [   "HouseGroundFloorWood_WallS",                           
                                "HouseGroundFloorWood_DoorS",                               
                                "HouseGroundFloorWood_WindowS",                               
                                "HouseGroundFloorWood_CornerSE",
                                "HouseGroundFloorWood_CornerSW",
                                "HouseGroundFloorWood_Air"]

tiles_possible_edge_west = [    "HouseGroundFloorWood_WallW",                           
                                "HouseGroundFloorWood_DoorW",                               
                                "HouseGroundFloorWood_WindowW",                               
                                "HouseGroundFloorWood_CornerNW",
                                "HouseGroundFloorWood_CornerSW",
                                "HouseGroundFloorWood_Air"]

tiles_possible_edge_bottom = [  "HouseGroundFloorWood_Ceiling",
                                "HouseGroundFloorWood_Stairs",
                                "HouseGroundFloorWood_WallN",
                                "HouseGroundFloorWood_WallE",
                                "HouseGroundFloorWood_WallS",
                                "HouseGroundFloorWood_WallW",
                                "HouseGroundFloorWood_DoorN",
                                "HouseGroundFloorWood_DoorE",
                                "HouseGroundFloorWood_DoorS",
                                "HouseGroundFloorWood_DoorW",
                                "HouseGroundFloorWood_WindowN",
                                "HouseGroundFloorWood_WindowE",
                                "HouseGroundFloorWood_WindowS",
                                "HouseGroundFloorWood_WindowW",
                                "HouseGroundFloorWood_CornerNE",
                                "HouseGroundFloorWood_CornerSE",
                                "HouseGroundFloorWood_CornerSW",
                                "HouseGroundFloorWood_CornerNW",
                                "HouseGroundFloorWood_Air"]


tile_rules = [  tiles_possible_all,
                tiles_possible_inner,
                tiles_possible_edge_north,
                tiles_possible_edge_east,
                tiles_possible_edge_top,
                tiles_possible_edge_south,
                tiles_possible_edge_west,
                tiles_possible_edge_bottom]
